---
title: "Problem Set 7"
author: "NAME HERE"
date: "10/8/2020"
output: pdf_document
---

https://data.cityofnewyork.us/Public-Safety/Motor-Vehicle-Collisions-Crashes/h9gi-nx95

```{r, include=F}
library(tidyverse)
df_motor <- read_csv("../data/Motor_Vehicle_Collisions_Crashes.csv")

df_motor <- df_motor %>%
  rename_with(~ tolower(gsub(" ","_", .x, fixed=TRUE))) %>%
  select(crash_date, crash_time, 
         number_of_persons_injured, number_of_pedestrians_injured, 
         number_of_cyclist_injured, number_of_motorist_injured, 
         contributing_factor_vehicle_1, 
         vehicle_type_code_1) %>% 
  drop_na()

df_motor %>%
  group_by(number_of_persons_injured) %>%
  summarize(count = n())

examine <- df_motor %>%
  group_by(vehicle_type_code_1) %>%
  summarize(count = n())

unique(df_motor$vehicle_type_code_1)

# lower case vehicles and add dash between spaces
df_motor <- df_motor %>%
  mutate(vehicle_type_code_1 = gsub(" ", "-", ignore.case=T, tolower(vehicle_type_code_1)))

# grab counts > 500
df_motor <- df_motor %>%
  group_by(vehicle_type_code_1) %>%
  mutate(count = n()) %>%
  filter(count > 500)

# calculate percentage by vehicle
viz <- df_motor %>%
  group_by(vehicle_type_code_1) %>%
  summarize(count = n(),
            perc = count/nrow(df_motor))

ggplot(viz, aes(x = vehicle_type_code_1, y = perc)) +
  geom_col()


```

```{r}
rat_reaction <- readxl::read_xlsx("../data/rat_reaction_time.xlsx")

# convert from wide to long
rat_reaction$subject <- factor(rat_reaction$subject)
rat_reaction_long <- re

# comparing order effects...maze 1 first leads to slower maze 2
rat_reaction %>%
  group_by(cond) %>%
  summarize(mean_1 = mean(maze_1),
            mean_2 = mean(maze_2))
```


group_by()

aggregate data
  + mean
  + sd
  + percent

flip from long to wide or vice versa